apiVersion: 1

datasources:

  - uid: machine-events
    name: OpenSearch - Machine Events
    type: grafana-opensearch-datasource
    access: proxy
    isDefault: true

    url: https://vpc-iot-platform-os-domain-alfusi76524i6uttderf7il64m.us-east-1.es.amazonaws.com

    basicAuth: true
    basicAuthUser: admin

    secureJsonData:
      basicAuthPassword: u2m.5!YvT-GkXP2

    jsonData:
      database: machine-events
      flavor: opensearch
      version: "3.5.0"
      timeField: timestamp
      maxConcurrentShardRequests: 5
      pplEnabled: true

    editable: true

  - uid: machine-aggregates
    name: OpenSearch - Machine Aggregates
    type: grafana-opensearch-datasource
    access: proxy

    url: https://vpc-iot-platform-os-domain-alfusi76524i6uttderf7il64m.us-east-1.es.amazonaws.com

    basicAuth: true
    basicAuthUser: admin

    secureJsonData:
      basicAuthPassword: u2m.5!YvT-GkXP2

    jsonData:
      database: machine-aggregates
      flavor: opensearch
      version: "3.5.0"
      timeField: window_start
      maxConcurrentShardRequests: 5
      pplEnabled: true

    editable: true

  - uid: worker-events
    name: OpenSearch - Worker Events
    type: grafana-opensearch-datasource
    access: proxy

    url: https://vpc-iot-platform-os-domain-alfusi76524i6uttderf7il64m.us-east-1.es.amazonaws.com

    basicAuth: true
    basicAuthUser: admin

    secureJsonData:
      basicAuthPassword: u2m.5!YvT-GkXP2

    jsonData:
      database: worker-events
      flavor: opensearch
      version: "3.5.0"
      timeField: timestamp
      maxConcurrentShardRequests: 5
      pplEnabled: true

    editable: true

  - uid: worker-safety
    name: OpenSearch - Worker Safety
    type: grafana-opensearch-datasource
    access: proxy

    url: https://vpc-iot-platform-os-domain-alfusi76524i6uttderf7il64m.us-east-1.es.amazonaws.com

    basicAuth: true
    basicAuthUser: admin

    secureJsonData:
      basicAuthPassword: u2m.5!YvT-GkXP2

    jsonData:
      database: worker-safety
      flavor: opensearch
      version: "3.5.0"
      timeField: window_start
      maxConcurrentShardRequests: 5
      pplEnabled: true

    editable: true